-- migration: cash_movements
create table public.cash_movements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  session_id bigint references public.cash_sessions on delete cascade not null,
  movement_type text not null check (movement_type in ('entrada', 'salida')),
  amount numeric not null,
  concept text not null,
  staff_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.cash_movements enable row level security;

-- Política de aislamiento
create policy "Users can CRUD own cash movements" on public.cash_movements
  for all using (auth.uid() = user_id);

-- Añadir columnas de métricas de movimientos a cash_cuts
alter table public.cash_cuts
  add column if not exists entradas_total numeric default 0,
  add column if not exists salidas_total numeric default 0;
