-- Security hardening for multi-tenant POS operation.
-- This migration closes permissive RLS policies and makes sale RPCs trust auth.uid().

create extension if not exists pgcrypto;

create table if not exists public.terminals (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  location text default '',
  machine_id text,
  is_main boolean default false,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.cash_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  staff_id bigint,
  staff_name text not null,
  opening_fund numeric default 0,
  status text default 'open',
  opened_at timestamptz default now(),
  closed_at timestamptz,
  terminal_id uuid references public.terminals(id)
);

create table if not exists public.active_carts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  session_id bigint,
  cart_data jsonb default '[]'::jsonb,
  total numeric default 0,
  payment_method text,
  amount_received numeric,
  change_amount numeric,
  status text default 'active',
  updated_at timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.active_carts
  add column if not exists user_id uuid references auth.users default auth.uid(),
  add column if not exists session_id bigint,
  add column if not exists cart_data jsonb default '[]'::jsonb,
  add column if not exists total numeric default 0,
  add column if not exists payment_method text,
  add column if not exists amount_received numeric,
  add column if not exists change_amount numeric,
  add column if not exists status text default 'active',
  add column if not exists updated_at timestamptz default now();

alter table public.cash_sessions
  add column if not exists user_id uuid references auth.users default auth.uid(),
  add column if not exists staff_id bigint,
  add column if not exists staff_name text,
  add column if not exists opening_fund numeric default 0,
  add column if not exists status text default 'open',
  add column if not exists opened_at timestamptz default now(),
  add column if not exists closed_at timestamptz,
  add column if not exists terminal_id uuid references public.terminals(id);

alter table public.terminals
  add column if not exists user_id uuid references auth.users default auth.uid(),
  add column if not exists location text default '',
  add column if not exists machine_id text,
  add column if not exists is_main boolean default false,
  add column if not exists is_active boolean default true,
  add column if not exists created_at timestamptz default now();

-- =====================================================
-- Customers: tenant isolation + credit fields
-- =====================================================
alter table public.customers
  add column if not exists user_id uuid references auth.users default auth.uid(),
  add column if not exists credit_limit numeric default 0,
  add column if not exists credit_balance numeric default 0,
  add column if not exists credit_hold boolean default false,
  add column if not exists payment_terms text default 'contado',
  add column if not exists credit_notes text default '';

alter table public.customers enable row level security;

drop policy if exists "Usuarios autenticados pueden leer clientes" on public.customers;
drop policy if exists "Usuarios autenticados pueden insertar clientes" on public.customers;
drop policy if exists "Usuarios autenticados pueden actualizar clientes" on public.customers;
drop policy if exists "Usuarios autenticados pueden eliminar clientes" on public.customers;
drop policy if exists "Users can CRUD own customers" on public.customers;

create policy "Users can CRUD own customers"
on public.customers
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists idx_customers_user_id on public.customers(user_id);

alter table public.sales
  add column if not exists customer_id uuid references public.customers(id),
  add column if not exists sale_type text default 'contado',
  add column if not exists paid_amount numeric default 0,
  add column if not exists balance numeric default 0,
  add column if not exists due_date date,
  add column if not exists credit_status text default null;

create index if not exists idx_sales_user_customer_credit
on public.sales(user_id, customer_id, credit_status);

create table if not exists public.sale_payments (
  id uuid default gen_random_uuid() primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  payment_method text not null,
  amount numeric not null,
  amount_received numeric not null,
  change_amount numeric default 0,
  currency text default 'MXN',
  exchange_rate numeric,
  created_at timestamptz default now()
);

-- =====================================================
-- Active carts and cash sessions: no public CRUD
-- =====================================================
alter table public.active_carts enable row level security;

drop policy if exists "Public users can CRUD active_carts" on public.active_carts;
drop policy if exists "Authenticated users can CRUD active_carts" on public.active_carts;
drop policy if exists "Allow anonymous read access to active_carts" on public.active_carts;
drop policy if exists "Users can CRUD own active_carts" on public.active_carts;

create policy "Users can CRUD own active_carts"
on public.active_carts
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists idx_active_carts_user_session
on public.active_carts(user_id, session_id);

alter table public.cash_sessions enable row level security;

drop policy if exists "Public users can CRUD cash_sessions" on public.cash_sessions;
drop policy if exists "Users can CRUD own cash_sessions" on public.cash_sessions;

create policy "Users can CRUD own cash_sessions"
on public.cash_sessions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists idx_cash_sessions_user_terminal_status
on public.cash_sessions(user_id, terminal_id, status);

-- =====================================================
-- Terminals and operational tables
-- =====================================================
alter table public.terminals enable row level security;

drop policy if exists "Users can CRUD own terminals" on public.terminals;
drop policy if exists "Public users can CRUD terminals" on public.terminals;
drop policy if exists "Authenticated users can CRUD terminals" on public.terminals;

create policy "Users can CRUD own terminals"
on public.terminals
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists idx_terminals_user_active
on public.terminals(user_id, is_active);

alter table public.cash_movements enable row level security;
drop policy if exists "Users can CRUD own cash movements" on public.cash_movements;
create policy "Users can CRUD own cash movements"
on public.cash_movements
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- sale_payments has no user_id, so isolate through its parent sale.
alter table public.sale_payments enable row level security;
drop policy if exists "Users can view their own sale payments" on public.sale_payments;
drop policy if exists "Users can insert own sale payments" on public.sale_payments;

create policy "Users can view their own sale payments"
on public.sale_payments
for select
to authenticated
using (
  exists (
    select 1 from public.sales s
    where s.id = sale_payments.sale_id
      and s.user_id = auth.uid()
  )
);

create policy "Users can insert own sale payments"
on public.sale_payments
for insert
to authenticated
with check (
  exists (
    select 1 from public.sales s
    where s.id = sale_payments.sale_id
      and s.user_id = auth.uid()
  )
);

-- =====================================================
-- Credit payments: create if needed and isolate by user_id
-- =====================================================
create table if not exists public.credit_payments (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  customer_id uuid references public.customers(id) on delete cascade not null,
  sale_id bigint references public.sales(id) on delete set null,
  amount numeric not null check (amount > 0),
  payment_method text default 'efectivo',
  reference text,
  notes text,
  created_at timestamptz default now()
);

alter table public.credit_payments enable row level security;

drop policy if exists "Users can CRUD own credit payments" on public.credit_payments;
create policy "Users can CRUD own credit payments"
on public.credit_payments
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists idx_credit_payments_user_customer
on public.credit_payments(user_id, customer_id);

-- =====================================================
-- Staff PIN hardening
-- =====================================================
alter table public.staff
  add column if not exists last_name text default '',
  add column if not exists permissions jsonb default '{"pos":true,"inventory":false,"reports":false,"reset_cash":false,"logout":false,"cut":true,"block":true}'::jsonb,
  add column if not exists auth_method text default 'pin',
  add column if not exists fingerprint_data text,
  add column if not exists pin_hash text;

alter table public.staff
  alter column pin drop not null;

update public.staff
set pin_hash = crypt(pin, gen_salt('bf'))
where pin_hash is null
  and pin is not null
  and pin <> '';

create or replace function public.validate_staff_pin(p_pin text)
returns table (
  id bigint,
  user_id uuid,
  name text,
  last_name text,
  role text,
  permissions jsonb,
  auth_method text,
  fingerprint_data text,
  active boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if p_pin is null or length(trim(p_pin)) < 4 or length(trim(p_pin)) > 6 then
    return;
  end if;

  return query
  select
    s.id,
    s.user_id,
    s.name,
    s.last_name,
    s.role,
    s.permissions,
    s.auth_method,
    s.fingerprint_data,
    s.active,
    s.created_at
  from public.staff s
  where s.user_id = auth.uid()
    and s.active = true
    and s.pin_hash = crypt(trim(p_pin), s.pin_hash)
  limit 1;
end;
$$;

grant execute on function public.validate_staff_pin(text) to authenticated;

create or replace function public.set_staff_pin(p_staff_id bigint, p_pin text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if p_pin is null or p_pin !~ '^[0-9]{4,6}$' then
    raise exception 'PIN invalido';
  end if;

  update public.staff
  set pin_hash = crypt(p_pin, gen_salt('bf')),
      pin = null
  where id = p_staff_id
    and user_id = auth.uid();

  if not found then
    raise exception 'Empleado no encontrado';
  end if;
end;
$$;

grant execute on function public.set_staff_pin(bigint, text) to authenticated;

-- =====================================================
-- Stock validation must be scoped to auth.uid()
-- =====================================================
create or replace function public.validate_sale_stock(p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_available numeric;
  v_errors jsonb := '[]'::jsonb;
  v_error jsonb;
begin
  for v_item in
    select * from jsonb_to_recordset(p_items)
      as x(product_id bigint, requested_base_qty numeric, name text)
  loop
    select stock into v_available
    from public.products
    where id = v_item.product_id
      and user_id = auth.uid();

    if v_available is null then
      v_error := jsonb_build_object(
        'product_id', v_item.product_id,
        'product_name', v_item.name,
        'error', 'Producto no encontrado',
        'available_stock', 0,
        'missing_qty', v_item.requested_base_qty
      );
      v_errors := v_errors || v_error;
    elsif v_available < v_item.requested_base_qty then
      v_error := jsonb_build_object(
        'product_id', v_item.product_id,
        'product_name', v_item.name,
        'available_stock', v_available,
        'requested_qty', v_item.requested_base_qty,
        'missing_qty', (v_item.requested_base_qty - v_available)
      );
      v_errors := v_errors || v_error;
    end if;
  end loop;

  return v_errors;
end;
$$;

grant execute on function public.validate_sale_stock(jsonb) to authenticated;

-- process_perfect_sale keeps the old signature for frontend compatibility,
-- but ignores p_user_id and uses auth.uid() as the tenant boundary.
create or replace function public.process_perfect_sale(
  p_total numeric,
  p_subtotal numeric default 0,
  p_tax_amount numeric default 0,
  p_user_id uuid default auth.uid(),
  p_currency text default 'MXN',
  p_exchange_rate numeric default null,
  p_amount_usd numeric default null,
  p_payment_method text default 'efectivo',
  p_terminal_id uuid default null,
  p_billing_issuer_id uuid default null,
  p_items jsonb default '[]'::jsonb,
  p_payments jsonb default '[]'::jsonb,
  p_affect_inventory boolean default true
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales%rowtype;
  v_item jsonb;
  v_payment jsonb;
  v_product_id bigint;
  v_quantity numeric;
  v_price numeric;
  v_total numeric;
  v_unit_sold text;
  v_conversion_factor integer;
  v_base_quantity numeric;
  v_available_stock numeric;
  v_errors jsonb := '[]'::jsonb;
  v_final_user_id uuid;
begin
  v_final_user_id := auth.uid();

  if v_final_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_terminal_id is not null and not exists (
    select 1 from public.terminals
    where id = p_terminal_id
      and user_id = v_final_user_id
      and coalesce(is_active, true) = true
  ) then
    raise exception 'Terminal no valida para esta tienda';
  end if;

  if p_affect_inventory then
    for v_item in select * from jsonb_array_elements(p_items)
    loop
      v_product_id := nullif(v_item->>'product_id', '')::bigint;
      v_conversion_factor := greatest(coalesce(nullif(v_item->>'conversion_factor', '')::integer, 1), 1);
      v_quantity := coalesce(nullif(v_item->>'quantity', '')::numeric, 0);
      v_base_quantity := coalesce(nullif(v_item->>'base_quantity', '')::numeric, v_quantity * v_conversion_factor);

      if v_product_id is not null then
        select stock into v_available_stock
        from public.products
        where id = v_product_id
          and user_id = v_final_user_id
        for update;

        if v_available_stock is null then
          v_errors := v_errors || jsonb_build_object(
            'product_name', coalesce(v_item->>'product_name', 'Desconocido'),
            'error', 'Producto no encontrado'
          );
        elsif v_available_stock < v_base_quantity then
          v_errors := v_errors || jsonb_build_object(
            'product_name', coalesce(v_item->>'product_name', 'Producto'),
            'available_stock', v_available_stock,
            'requested_qty', v_base_quantity,
            'missing_qty', v_base_quantity - v_available_stock
          );
        end if;
      end if;
    end loop;

    if jsonb_array_length(v_errors) > 0 then
      raise exception 'Stock insuficiente detectado en el servidor: %', v_errors::text;
    end if;
  end if;

  insert into public.sales (
    user_id,
    total,
    subtotal,
    tax_amount,
    currency,
    exchange_rate,
    amount_usd,
    payment_method,
    terminal_id,
    billing_issuer_id,
    pin_facturacion
  )
  values (
    v_final_user_id,
    p_total,
    coalesce(p_subtotal, 0),
    coalesce(p_tax_amount, 0),
    coalesce(p_currency, 'MXN'),
    p_exchange_rate,
    p_amount_usd,
    coalesce(p_payment_method, 'efectivo'),
    p_terminal_id,
    p_billing_issuer_id,
    upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6))
  )
  returning * into v_sale;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_product_id := nullif(v_item->>'product_id', '')::bigint;
    v_quantity := coalesce(nullif(v_item->>'quantity', '')::numeric, 0);
    v_price := coalesce(nullif(v_item->>'price', '')::numeric, 0);
    v_total := coalesce(nullif(v_item->>'total', '')::numeric, v_price * v_quantity);
    v_unit_sold := case when v_item->>'unit_sold' = 'CAJA' then 'CAJA' else 'PZA' end;
    v_conversion_factor := greatest(coalesce(nullif(v_item->>'conversion_factor', '')::integer, 1), 1);
    v_base_quantity := coalesce(nullif(v_item->>'base_quantity', '')::numeric, v_quantity * v_conversion_factor);

    insert into public.sale_items (
      sale_id,
      user_id,
      product_id,
      product_name,
      quantity,
      price,
      total,
      unit_sold,
      conversion_factor,
      base_quantity
    )
    values (
      v_sale.id,
      v_sale.user_id,
      v_product_id,
      coalesce(v_item->>'product_name', 'Producto'),
      v_quantity,
      v_price,
      v_total,
      v_unit_sold,
      v_conversion_factor,
      v_base_quantity
    );

    if p_affect_inventory and v_product_id is not null then
      update public.products
      set stock = stock - v_base_quantity
      where id = v_product_id
        and user_id = v_sale.user_id;
    end if;
  end loop;

  if p_payments is not null and jsonb_array_length(p_payments) > 0 then
    for v_payment in select * from jsonb_array_elements(p_payments)
    loop
      insert into public.sale_payments (
        sale_id,
        payment_method,
        amount,
        amount_received,
        change_amount,
        currency,
        exchange_rate
      )
      values (
        v_sale.id,
        coalesce(v_payment->>'payment_method', 'efectivo'),
        coalesce((v_payment->>'amount')::numeric, 0),
        coalesce((v_payment->>'amount_received')::numeric, 0),
        coalesce((v_payment->>'change_amount')::numeric, 0),
        coalesce(v_payment->>'currency', 'MXN'),
        nullif(v_payment->>'exchange_rate', '')::numeric
      );
    end loop;
  else
    insert into public.sale_payments (
      sale_id,
      payment_method,
      amount,
      amount_received,
      change_amount,
      currency,
      exchange_rate
    )
    values (
      v_sale.id,
      coalesce(p_payment_method, 'efectivo'),
      p_total,
      p_total,
      0,
      p_currency,
      p_exchange_rate
    );
  end if;

  return v_sale;
end;
$$;

grant execute on function public.process_perfect_sale(
  numeric, numeric, numeric, uuid, text, numeric, numeric, text, uuid, uuid, jsonb, jsonb, boolean
) to authenticated;

-- =====================================================
-- Store vertical defaults for future industry-specific UX.
-- =====================================================
alter table public.profiles
  add column if not exists business_vertical text default 'general'
    check (business_vertical in ('general', 'ferreteria', 'abarrotes', 'refaccionaria', 'papeleria')),
  add column if not exists enabled_units jsonb default '["PZA","CAJA"]'::jsonb;

-- Credit sale wrapper: one transaction for sale, stock, sale credit fields, payment, and customer balance.
create or replace function public.process_credit_sale(
  p_total numeric,
  p_subtotal numeric default 0,
  p_tax_amount numeric default 0,
  p_currency text default 'MXN',
  p_payment_method text default 'credito',
  p_terminal_id uuid default null,
  p_items jsonb default '[]'::jsonb,
  p_payments jsonb default '[]'::jsonb,
  p_affect_inventory boolean default true,
  p_customer_id uuid default null,
  p_paid_amount numeric default 0,
  p_balance numeric default 0,
  p_due_date date default null
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales%rowtype;
  v_user_id uuid := auth.uid();
  v_balance numeric := greatest(coalesce(p_balance, p_total - coalesce(p_paid_amount, 0)), 0);
  v_status text;
begin
  if v_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_customer_id is null then
    raise exception 'Cliente requerido para venta a credito';
  end if;

  if not exists (
    select 1 from public.customers
    where id = p_customer_id
      and user_id = v_user_id
      and coalesce(credit_hold, false) = false
  ) then
    raise exception 'Cliente no valido o con credito bloqueado';
  end if;

  v_sale := public.process_perfect_sale(
    p_total,
    p_subtotal,
    p_tax_amount,
    null,
    p_currency,
    null,
    null,
    p_payment_method,
    p_terminal_id,
    null,
    p_items,
    p_payments,
    p_affect_inventory
  );

  v_status := case
    when v_balance <= 0 then 'pagado'
    when coalesce(p_paid_amount, 0) > 0 then 'parcial'
    else 'pendiente'
  end;

  update public.sales
  set customer_id = p_customer_id,
      sale_type = 'credito',
      paid_amount = coalesce(p_paid_amount, 0),
      balance = v_balance,
      due_date = p_due_date,
      credit_status = v_status
  where id = v_sale.id
    and user_id = v_user_id
  returning * into v_sale;

  update public.customers
  set credit_balance = coalesce(credit_balance, 0) + v_balance
  where id = p_customer_id
    and user_id = v_user_id;

  if coalesce(p_paid_amount, 0) > 0 then
    insert into public.credit_payments (
      user_id,
      customer_id,
      sale_id,
      amount,
      payment_method,
      notes
    )
    values (
      v_user_id,
      p_customer_id,
      v_sale.id,
      p_paid_amount,
      p_payment_method,
      'Anticipo registrado al crear la venta'
    );
  end if;

  return v_sale;
end;
$$;

grant execute on function public.process_credit_sale(
  numeric, numeric, numeric, text, text, uuid, jsonb, jsonb, boolean, uuid, numeric, numeric, date
) to authenticated;
